import{a as v,S as w,i}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const q="50358243-9944b3624f9c71a45bbdf1549",S="https://pixabay.com/api/";async function m(s,r){try{return(await v.get(S,{params:{key:q,q:s,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch{throw new Error("Не удалось загрузить изображения с Pixabay")}}const E=new w(".gallery a",{captionsData:"alt",captionDelay:250}),y=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more");function p(s){const r=s.map(e=>`
        <a href="${e.largeImageURL}" class="gallery-item">
          <img src="${e.webformatURL}" alt="${e.tags}" />
          <div class="info">
            <p>Likes: ${e.likes}</p>
            <p>Views: ${e.views}</p>
            <p>Comments: ${e.comments}</p>
            <p>Downloads: ${e.downloads}</p>
          </div>
        </a>
      `).join("");y.insertAdjacentHTML("beforeend",r),E.refresh()}function P(){y.innerHTML=""}function L(){g.classList.add("visible")}function l(){g.classList.remove("visible")}function b(){h.classList.add("visible")}function u(){h.classList.remove("visible")}const $=document.querySelector(".search-form"),B=document.querySelector(".load-more");let f="",n=1,c=0;$.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements.query.value.trim();if(!r){i.error({title:"Error",message:"Please enter a search query!"});return}f=r,n=1,P(),u(),L();try{const e=await m(f,n);l(),c=e.totalHits;const a=e.hits;if(a.length===0){i.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(a),i.success({title:"Success",message:`Found ${c} images!`}),a.length<15||n*15>=c?(u(),n*15>=c&&i.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."})):b()}catch{l(),i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});B.addEventListener("click",async()=>{n+=1,L(),u();try{const s=await m(f,n);l();const r=s.hits;p(r);const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}r.length<15||n*15>=c?(u(),n*15>=c&&i.info({title:"End of Collection",message:"We're sorry, but you've reached the end of search results."})):b()}catch{l(),i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}});
//# sourceMappingURL=index.js.map
