import{a as v,S as w,i as n}from"./assets/vendor-CrlV4O_2.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const q="50358243-9944b3624f9c71a45bbdf1549",S="https://pixabay.com/api/";async function m(s,r){try{return(await v.get(S,{params:{key:q,q:s,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch{throw new Error("Не удалось загрузить изображения с Pixabay")}}const $=new w(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.querySelector(".gallery"),y=document.querySelector(".loader"),g=document.querySelector(".load-more");function h(s){const r=s.map(e=>`
        <li>
          <a href="${e.largeImageURL}" class="gallery-item">
            <img src="${e.webformatURL}" alt="${e.tags}" />
            <div class="info">
              <p>Лайки: ${e.likes}</p>
              <p>Просмотры: ${e.views}</p>
              <p>Комментарии: ${e.comments}</p>
              <p>Скачивания: ${e.downloads}</p>
            </div>
          </a>
        </li>
      `).join("");p.insertAdjacentHTML("beforeend",r),$.refresh()}function B(){p.innerHTML=""}function L(){y.classList.add("visible")}function l(){y.classList.remove("visible")}function b(){g.classList.add("visible")}function u(){g.classList.remove("visible")}const M=document.querySelector(".form"),P=document.querySelector(".load-more");let f="",a=1,c=0;M.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements.query.value.trim();if(!r){n.error({title:"Ошибка",message:"Введите поисковый запрос!"});return}f=r,a=1,B(),u(),L();try{const e=await m(f,a);l(),c=e.totalHits;const i=e.hits;if(i.length===0){n.warning({title:"Нет результатов",message:"Извините, по вашему запросу ничего не найдено. Попробуйте снова!"});return}h(i),n.success({title:"Успех",message:`Найдено ${c} изображений!`}),i.length<15||a*15>=c?(u(),a*15>=c&&n.info({title:"Конец коллекции",message:"Извините, вы достигли конца результатов поиска."})):b()}catch{l(),n.error({title:"Ошибка",message:"Не удалось загрузить изображения. Попробуйте снова!"})}});P.addEventListener("click",async()=>{a+=1,L(),u();try{const s=await m(f,a);l();const r=s.hits;h(r);const e=document.querySelector(".gallery-item");if(e){const i=e.getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}r.length<15||a*15>=c?(u(),a*15>=c&&n.info({title:"Конец коллекции",message:"Извините, вы достигли конца результатов поиска."})):b()}catch{l(),n.error({title:"Ошибка",message:"Не удалось загрузить изображения. Попробуйте снова!"})}});
//# sourceMappingURL=index.js.map
